# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-26 22:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='main',
            field=models.BooleanField(default=False, verbose_name='On Homepage'),
        ),
    ]
