# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-27 21:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_tag_main'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='tags',
            field=models.ManyToManyField(to='forum.Tag', verbose_name='Tags'),
        ),
    ]
