# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-03 21:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_auto_20160729_1857'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'permissions': (('edit_not_owned_message', 'Can edit messages authored by someone else'),)},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'permissions': (('view_tag', 'Can view content associated with tag'),)},
        ),
    ]
