# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-03 22:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
        ('forum', '0006_auto_20160803_2144'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='only_for',
            field=models.ManyToManyField(to='auth.Group', verbose_name='Allowed Groups'),
        ),
    ]
