# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-14 10:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0007_tag_only_for'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='cover_image',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
