# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-15 23:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0008_tag_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='post_it',
            field=models.BooleanField(default=False, verbose_name='Post-it'),
        ),
    ]
