# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-15 23:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0009_topic_post_it'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='banned',
            field=models.BooleanField(default=False, verbose_name='Is banned'),
        ),
    ]
