# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-16 18:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0010_profile_banned'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='closed',
            field=models.BooleanField(default=False, verbose_name='Closed'),
        ),
    ]
