# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-16 23:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0011_topic_closed'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.URLField(default='static/anonymous_avatar.png', verbose_name='Avatar URL'),
        ),
    ]
