# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-16 23:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0012_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.CharField(default='/static/anonymous_avatar.png', max_length=200, verbose_name='Avatar URL'),
        ),
    ]
