# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-08 16:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forum', '0015_auto_20160819_2338'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='private_viewers',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
