# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-13 00:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0017_auto_20161110_0235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='only_for',
            field=models.ManyToManyField(blank=True, to='auth.Group', verbose_name='Allowed Groups'),
        ),
    ]
