# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-13 00:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0018_auto_20161113_0038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='private_viewers',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
